
spring:
  application:
     name: SellerProfile



# Discovery Server Access

#eureka:
 # client:
    #serviceUrl:
     # defaultZone: http://127.0.0.1:8761/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

 # database Properties
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
    
